default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: bambam_development

test: &test
  <<: *default
  database: bambam_test

production: &production
  <<: *default
  database: <%= ENV['DB_USERNAME'] %>_bambam_production

staging:
  <<: *production
  database: <%= ENV['DB_USERNAME'] %>_bambam_staging

cucumber:
  <<: *test
